on:
  workflow_dispatch:
  schedule: 
   - cron: "1 1 28 * *"

name: update_results

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::tidyverse
            any::httr
            any::rvest
            any::tsibble
            any::fable
            any::fabletools
            any::feasts
            any::lubridate
            any::haven
            
      - name: run-script
        run: |
          Rscript nino.R
          Rscript sst.R
          Rscript ice.R
          Rscript tropo.R
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
